version: '3.8'
services:
  db-movies-manager:
    container_name: nestjs-movies-manager
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - conexa
  test-db-movies-manager:
    container_name: nestjs-movies-manager-test-db
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - conexa
networks:
  conexa:
